// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCimOqX9KxexPrcwdqmnNWkaMd7Cq0bkZc',
    appId: '1:288255702603:web:64c4e5d82448a7bc7c3fce',
    messagingSenderId: '288255702603',
    projectId: 'houseloo',
    authDomain: 'houseloo.firebaseapp.com',
    storageBucket: 'houseloo.firebasestorage.app',
    measurementId: 'G-LM65QDM5WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-Xd9csbmMutHT5aBNejPGLFUje5nDQ8',
    appId: '1:288255702603:android:8b6c7502132f73ce7c3fce',
    messagingSenderId: '288255702603',
    projectId: 'houseloo',
    storageBucket: 'houseloo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkaE1yzAkZSwFQ54y_vrYnXGgkP_ygSgA',
    appId: '1:288255702603:ios:454e8cb0fddaa5fa7c3fce',
    messagingSenderId: '288255702603',
    projectId: 'houseloo',
    storageBucket: 'houseloo.firebasestorage.app',
    iosBundleId: 'com.example.houseloo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkaE1yzAkZSwFQ54y_vrYnXGgkP_ygSgA',
    appId: '1:288255702603:ios:454e8cb0fddaa5fa7c3fce',
    messagingSenderId: '288255702603',
    projectId: 'houseloo',
    storageBucket: 'houseloo.firebasestorage.app',
    iosBundleId: 'com.example.houseloo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCimOqX9KxexPrcwdqmnNWkaMd7Cq0bkZc',
    appId: '1:288255702603:web:df8eb55c01a1aaec7c3fce',
    messagingSenderId: '288255702603',
    projectId: 'houseloo',
    authDomain: 'houseloo.firebaseapp.com',
    storageBucket: 'houseloo.firebasestorage.app',
    measurementId: 'G-1BG7FMKVGC',
  );
}
